# Generated by Django 4.0.4 on 2022-05-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=255)),
                ('remote', models.BooleanField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('seniority', models.CharField(max_length=255)),
            ],
        ),
    ]
