# Generated by Django 4.0.4 on 2022-05-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_date_remove_job_seniority'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
