# Generated by Django 4.0.4 on 2022-05-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='seniority',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
