# Generated by Django 4.0.4 on 2022-05-24 05:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_glassdoor_alter_company_linkedin_and_more'),
        ('jobs', '0007_job_seniority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='seniority',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
