# Generated by Django 4.0.4 on 2022-05-24 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_glassdoor_alter_company_linkedin_and_more'),
        ('jobs', '0009_remove_job_company_job_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='companies.company'),
        ),
    ]
