# Generated by Django 4.0.4 on 2022-05-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_glassdoor_alter_company_linkedin_and_more'),
        ('jobs', '0014_remove_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
