# Generated by Django 4.0.4 on 2022-07-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
