# Generated by Django 4.0.4 on 2022-08-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_remove_job_id_alter_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
