version: '3.8'
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=datatrampos
      - POSTGRES_PASSWORD=datatrampos
      - POSTGRES_DB=datatrampos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
