# Generated by Django 3.1.7 on 2021-05-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('job_title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=70)),
                ('remote', models.CharField(max_length=6)),
                ('workplace', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
