# Generated by Django 4.0.4 on 2022-05-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('glassdoor', models.CharField(max_length=250)),
                ('logo', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
