# Generated by Django 4.0.4 on 2023-01-12 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_active_company_haveopenings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='haveOpenings',
        ),
    ]
